#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/clone/test ensure=absent force=true
puppet resource file /tmp/clone/test ensure=directory
cd /tmp/clone/test
git clone https://github.com/KyawRP/dev_ops_repo.git
cp -p /tmp/clone/test/dev_ops_repo/index.html /var/www/html
