#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/clone ensure=absent force=true
puppet resource file /tmp/clone ensure=directory
cd /tmp/clone
git clone https://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@KyawRP/dev_ops_repo.git
cp -p /tmp/clone/devops_repo/index.html /var/www/html
